using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace CommonCore.State
{
    //DO NOT EDIT THIS FILE

    /// <summary>
    /// What the upcoming scene transition is intended to do
    /// </summary>
    public enum SceneTransitionType
    {
        NewGame, LoadGame, ChangeScene
    }

    /// <summary>
    /// Represents the state of the current game session
    /// </summary>
    public sealed partial class MetaState
    {
        
        private static MetaState instance;

        private MetaState()
        {
        }

        public static MetaState Instance
        {
            get
            {
                if (instance == null)
                {
                    instance = new MetaState();
                }
                return instance;
            }
        }

        /// <summary>
        /// Soft-resets session state related to the game world
        /// </summary>
        public void Clear()
        {
            Intents.Clear();
            LoadSave = null;
            PreviousScene = null;
            NextScene = null;
            SkipLoadingScreen = false;
        }

        /// <summary>
        /// Purges the current sessions state
        /// </summary>
        public static void Reset()
        {
            instance = new MetaState();
        }

        //TODO refactor the way Intents work

        public void IntentsExecutePreload()
        {
            Debug.Log(string.Format("Executing intents preload ({0} total)", Intents.Count));
            foreach (Intent i in Intents)
            {
                i.PreloadExecute();
            }
        }

        public void IntentsExecutePostload()
        {
            Debug.Log(string.Format("Executing intents postload ({0} total)", Intents.Count));
            foreach (Intent i in Intents)
            {
                i.PostloadExecute();
            }
        }

        public void IntentsExecuteLoading()
        {
            Debug.Log(string.Format("Executing intents loading ({0} total)", Intents.Count));
            foreach (Intent i in Intents)
            {
                i.LoadingExecute();
            }
        }

        //Actual instance data (shared across game types)

        public SceneTransitionType TransitionType { get; set; }
        public string PreviousScene { get; set; }
        public string NextScene { get; set; }
        public string LoadSave { get; set; }        
        public bool SkipLoadingScreen { get; set; }
        public HashSet<string> SessionFlags { get; set; } = new HashSet<string>();
        public List<Intent> Intents { get; set; } = new List<Intent>();
    }
}
