namespace CommonCore.State
{
    //DO NOT EDIT THIS FILE

    public partial class GameState
    {
        /// <summary>
        /// [Campaign] State data of the RPG campaign (quests, flags, etc)
        /// </summary>
        public CampaignModel CampaignState { get; private set; } = new CampaignModel();


    }

}