using CommonCore.World;
using System.Collections.Generic;

namespace CommonCore.State
{
    //DO NOT EDIT THIS FILE UNLESS YOU ARE MAKING CHANGES TO THE WORLD MODULE

    public partial class GameState
    {
        /// <summary>
        /// [World] Restorable object state for scene-local objects
        /// </summary>
        public Dictionary<string, Dictionary<string, RestorableData>> LocalObjectState { get; private set; } = new Dictionary<string, Dictionary<string, RestorableData>>();

        /// <summary>
        /// [World] Restorable object state for motile objects (not tied to scenes)
        /// </summary>
        public Dictionary<string, RestorableData> MotileObjectState { get; private set; } = new Dictionary<string, RestorableData>();
        
        /// <summary>
        /// [World] Restorable object state for the player object
        /// </summary>
        public RestorableData PlayerWorldState { get; set; }

        /// <summary>
        /// [World] Player flags, stores some and handles those from other sources
        /// </summary>
        public PlayerFlagsCollection PlayerFlags { get; private set; } = new PlayerFlagsCollection();

    }

}