using CommonCore.World;
using System.ComponentModel;

namespace CommonCore.State
{
    //DO NOT EDIT THIS FILE UNLESS YOU ARE MAKING CHANGES TO THE WORLD MODULE

    public sealed partial class MetaState
    {
        /// <summary>
        /// [World] The spawn intent for the player 
        /// </summary>
        [DefaultValue((object)null), Clear]
        public PlayerSpawnIntent PlayerIntent { get; set; }

    }



}