using CommonCore.World;

namespace CommonCore.State
{
    //DO NOT EDIT THIS FILE UNLESS YOU ARE MAKING CHANGES TO THE WORLD MODULE

    public sealed partial class MetaState
    {
        /// <summary>
        /// [World] The spawn intent for the player 
        /// </summary>
        public PlayerSpawnIntent PlayerIntent { get; set; } //horrible for cleanliness but should be faster

    }



}